const assert=require('node:assert/strict'),test=require('node:test');
const categories=require('../server/ops-functions/topuyi-ops-v1/categories');
const storefront=require('../server/ops-functions/topuyi-ops-v1/publish-storefront');
const config=(names)=>({version:1,blocks:[{id:'goods',type:'products',visible:true,items:names.map((category,n)=>({id:'item'+n,sku:'sku'+n,title:'商品'+n,category,price:10,image:'cloud://image'}))}]});
const user={name:'本地测试'};
function dbFixture(seed){let state=structuredClone(seed);const source=()=>({collection:name=>({doc:id=>({get:async()=>({data:state[name+'/'+id]?[structuredClone(state[name+'/'+id])]:[]}),set:async value=>{state[name+'/'+id]=structuredClone(value);}})})});return {...source(),runTransaction:async fn=>{const before=structuredClone(state);try{return await fn(source());}catch(e){state=before;throw e;}},state:()=>structuredClone(state)};}
test('旧分类去空格、去重复，生成稳定标识，保留未分类商品原默认值',()=>{const a=config([' 手环 ','手环','LED','led',undefined]),before=structuredClone(a),r=categories.migrate([a]);assert.deepEqual(r.items.map(c=>c.name),['手环','LED','荧光棒']);assert.deepEqual(r,categories.migrate([a]));assert.deepEqual(a,before);const n=categories.normalize(a,r);assert.equal(n.blocks[0].items[0].categoryId,n.blocks[0].items[1].categoryId);assert.equal(n.blocks[0].items[3].category,'LED');});
test('改名保留商品关联和旧名称映射，已发布快照不变',()=>{const draft={config:config(['手环'])},s={draft,live:structuredClone(draft)},original=structuredClone(s),r=categories.migrate([draft.config]);s.record=r;const next=categories.change(s,{operation:'rename',id:r.items[0].id,name:'发光手环',expectedRevision:null},user);const fromOld=categories.normalize(draft.config,next),fromId=categories.normalize(categories.normalize(draft.config,r),next);assert.deepEqual(fromOld,fromId);assert.equal(fromOld.blocks[0].items[0].category,'发光手环');assert.equal(fromOld.categories[0].aliases,undefined);assert.deepEqual(s.live,original.live);assert.throws(()=>categories.normalize(config(['未知分类']),next),/分类不存在/);});
test('分类名称校验、重名、旧名占用和多人更新冲突',()=>{const s={record:categories.migrate([config(['手环','挂件'])])},id=s.record.items[0].id;for(const name of ['','  ','x'.repeat(21),'全部商品',' 挂件 '])assert.throws(()=>categories.change(s,{operation:'rename',id,name,expectedRevision:null},user));const r=categories.change(s,{operation:'rename',id,name:'发光手环',expectedRevision:null},user);assert.throws(()=>categories.change({record:r},{operation:'add',name:'灯牌',expectedRevision:null},user),/同事已更新/);assert.throws(()=>categories.change({record:r},{operation:'add',name:'手环',expectedRevision:r.revision},user),/旧名称占用/);});
test('草稿、已发布和模板引用均阻止删除，空分类可删除且顺序必须完整',()=>{const r=categories.migrate([config(['手环','挂件'])]),id=r.items[0].id;for(const s of [{draft:{config:config(['手环'])}},{live:{config:config(['手环'])}},{templates:{items:[{config:config(['手环'])}]}}])assert.throws(()=>categories.change({...s,record:r},{operation:'delete',id,expectedRevision:null},user),/仍被使用/);const next=categories.change({record:r},{operation:'delete',id,expectedRevision:null},user);assert.equal(next.items.length,1);assert.throws(()=>categories.change({record:r},{operation:'reorder',ids:[id,id],expectedRevision:null},user),/顺序不完整/);assert.equal(categories.change({record:r},{operation:'reorder',ids:r.items.map(c=>c.id).reverse(),expectedRevision:null},user).items[0].name,'挂件');});
test('分类读取不写数据；事务保存和发布时校验分类版本',async()=>{const cfg=config(['手环']),draft={config:cfg,revision:'draft-1'},db=dbFixture({'topuyi_ops_content_v1/draft':draft});const initial=db.state(),r=await categories.handle(db,{action:'categoriesLoad'},user);assert.deepEqual(db.state(),initial);const changed=await categories.handle(db,{action:'categoriesUpdate',operation:'add',name:'挂件',expectedRevision:null},user);assert.equal(changed.items.length,2);await assert.rejects(()=>categories.assertRevision(db,null),/分类已更新/);const snapshot=categories.normalize(cfg,changed);await storefront.publish(db,snapshot,{expectedDraftRevision:'draft-1',expectedRevision:null},user);const published=db.state()['topuyi_storefront_live_v1/active'];assert.deepEqual(published.config.categories,snapshot.categories);assert.equal(published.config.blocks[0].items[0].category,'手环');await categories.handle(db,{action:'categoriesUpdate',operation:'rename',id:r.items[0].id,name:'新手环',expectedRevision:changed.revision},user);const before=db.state();await assert.rejects(()=>storefront.publish(db,snapshot,{expectedDraftRevision:'draft-1',expectedRevision:published.revision},user),/分类已更新/);assert.deepEqual(db.state(),before);});
