'use client';
import {useEffect,useState} from 'react';
import {ArrowUp,ArrowDown,Plus,Monitor} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {SidebarTrigger} from '@/components/ui/sidebar';
import {useCategories,type Category} from '@/lib/categories';
export default function CategoryManager({onHome}:{onHome:()=>void}){
 const state=useCategories()!,[editing,setEditing]=useState<Category|'new'|null>(null),[name,setName]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState('');
 useEffect(()=>{void state.refresh();},[state.refresh]);
 const items=state.data?.items||[];
 function edit(c:Category|'new'){setEditing(c);setName(c==='new'?'':c.name);setError('');}
 async function save(){try{await state.mutate({operation:editing==='new'?'add':'rename',id:editing&&editing!=='new'?editing.id:undefined,name});setEditing(null);setNotice('分类已保存。请返回首页装修保存共享草稿，再发布商城。');}catch(e){setError(e instanceof Error?e.message:'保存失败。');}}
 async function move(index:number,step:number){const ids=items.map(c=>c.id);[ids[index],ids[index+step]]=[ids[index+step],ids[index]];try{await state.mutate({operation:'reorder',ids});setNotice('分类顺序已保存，保存共享草稿并发布商城后在手机端生效。');}catch{}}
 async function remove(c:Category){if(!window.confirm(`删除分类“${c.name}”？`))return;try{await state.mutate({operation:'delete',id:c.id});setNotice('分类已删除，请返回首页装修保存共享草稿并发布商城。');}catch{}}
 return <><main className="workspace"><header className="topbar"><div className="crumb"><SidebarTrigger/><span>店铺管理</span><b>商品分类</b></div><div className="top-actions"><Button variant="outline" disabled={state.busy} onClick={()=>void state.refresh()}>刷新分类</Button><Button disabled={state.busy||!state.data||items.length>=100} onClick={()=>edit('new')}><Plus/>新增分类</Button></div></header><div className="page-heading"><div><h1>商品分类</h1><p>统一维护分类名称，编辑商品时直接下拉选择。</p></div><span>{items.length} / 100 个分类</span></div><div className="scope-note"><Monitor size={16}/><span>分类保存后即可在后台选择；手机端需在首页装修保存共享草稿，再发布商城。没有商品的分类不在手机端展示。</span></div>{(state.error||notice)&&<output className="feedback" role="status">{state.error||notice}</output>}<section className="category-table"><table><thead><tr><th>顺序</th><th>分类名称</th><th>草稿商品</th><th>已发布商品</th><th>操作</th></tr></thead><tbody>{items.map((c,n)=>{const used=state.data?.usage[c.id],inUse=!!used&&(used.draft+used.published+used.templates>0);return <tr key={c.id}><td>{n+1}</td><td><strong>{c.name}</strong></td><td>{used?.draft||0}</td><td>{used?.published||0}</td><td><div className="category-actions"><Button variant="ghost" size="icon" aria-label={`上移 ${c.name}`} disabled={!n||state.busy} onClick={()=>void move(n,-1)}><ArrowUp/></Button><Button variant="ghost" size="icon" aria-label={`下移 ${c.name}`} disabled={n===items.length-1||state.busy} onClick={()=>void move(n,1)}><ArrowDown/></Button><Button variant="outline" disabled={state.busy} onClick={()=>edit(c)}>改名</Button><Button variant="ghost" disabled={state.busy||inUse} onClick={()=>void remove(c)}>删除</Button></div>{inUse&&<small>使用中：先调整商品归属并保存、发布{used?.templates?'，同时清理引用此分类的模板':''}</small>}</td></tr>;})}</tbody></table>{!state.data?<p>正在读取分类。{state.error?'请点击刷新分类重试。':''}</p>:!items.length&&<p>还没有商品分类，请点击“新增分类”。</p>}</section><Button variant="outline" onClick={onHome}>返回首页装修</Button></main><Dialog open={editing!==null} onOpenChange={v=>!v&&setEditing(null)}><DialogContent><DialogTitle>{editing==='new'?'新增商品分类':'修改分类名称'}</DialogTitle><DialogDescription>分类名称最多 20 个字。改名后关联商品保留原分类归属。</DialogDescription><Input aria-label="分类名称" maxLength={20} value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&name.trim()&&!state.busy){e.preventDefault();void save();}}}/>{error&&<p role="alert">{error}</p>}<Button disabled={state.busy||!name.trim()} onClick={()=>void save()}>{state.busy?'保存中…':'保存分类'}</Button></DialogContent></Dialog></>;
}
