'use client';
/* Local data-URL images need no server optimization; user videos may not include captions. */
/* oxlint-disable next/no-img-element, jsx-a11y/media-has-caption */
import {useEffect,useRef,useState,type ReactNode,type CSSProperties} from 'react';
import {ImagePlus,PanelsTopLeft,Film,Grid2X2,ShoppingBag,BookOpen,GripVertical,Plus,Eye,EyeOff,Save,Download,Upload,Copy,Trash2,ArrowUp,ArrowDown,Smartphone,Check,FolderOpen,ChevronRight,X,Monitor,Undo2,Redo2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Switch} from '@/components/ui/switch';
import {Slider} from '@/components/ui/slider';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from '@/components/ui/sidebar';
import {defaults,newBlock,newItem,validateConfig,readRecord,writeRecord,type Config,type Block,type Item,type Kind,kinds,targets,colors} from '@/lib/editor';
import {ops,uploadMedia,migrateMedia} from '@/lib/ops-client';
const icons={banner:PanelsTopLeft,video:Film,links:Grid2X2,poster:ImagePlus,products:ShoppingBag,about:BookOpen};
type Product=import('@/lib/ops-types').Product;
type SavedTemplate={id:string;name:string;date:string;config:Config};
function Field({title,children}:{title:string;children:ReactNode}){return <label className="field"><span>{title}</span>{children}</label>;}
function Choice({value,values,onChange}:{value:string;values:string[];onChange:(v:string)=>void}){return <Select value={value} onValueChange={v=>v!==null&&onChange(v)}><SelectTrigger className="choice"><SelectValue>{value}</SelectValue></SelectTrigger><SelectContent>{values.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>;}
function Media({src,className='',style}:{src:string;className?:string;style?:CSSProperties}){return src?<img style={style} className={className} src={src} alt="模块图片"/>:<div style={style} className={'empty-media '+className}><ImagePlus size={26}/><span>添加图片</span></div>;}
function Preview({config,selected,onSelect,interactive=false,catalog=[]}:{catalog?:Product[];config:Config;selected:string;onSelect:(id:string)=>void;interactive?:boolean}){
 const [slides,setSlides]=useState<Record<string,number>>({});
 return <div className="phone"><div className="phone-status"><b>9:41</b><span>● ▰ ▰</span></div><div className="phone-brand"><b>TOPUYI</b><span>拓普依智能灯光</span><span className="capsule">••• │ ○</span></div><div className="phone-page">{config.blocks.filter(b=>b.visible).map(b=>{
 const active=Math.min(slides[b.id]||0,b.items.length-1),hero=b.items[active],dark=['#171b26','#202733'].includes(b.background);
 return <section key={b.id} className={`preview-block ${b.type} ${selected===b.id&&!interactive?'is-selected':''} ${dark?'dark-block':''}`} style={{background:b.background,marginBottom:b.spacing}} aria-label={b.title}>
 {!interactive&&<button className="preview-select" aria-label={'编辑 '+b.title} onClick={()=>onSelect(b.id)}/>}
 {!interactive&&selected===b.id&&<span className="selected-tag">正在编辑 · {kinds[b.type]}</span>}
 {b.showHeading!==false&&(b.title||b.subtitle)&&<div className="module-heading">{b.title&&<h3>{b.title}</h3>}{b.subtitle&&<p className="block-description">{b.subtitle}</p>}</div>}
 {b.type==='banner'?<><div className="hero-preview" style={{minHeight:b.height/2}}><Media src={hero.image} className="hero-image"/></div><div className="dots">{b.items.map((i,n)=><button key={i.id} className={active===n?'on':''} onClick={e=>{e.stopPropagation();setSlides({...slides,[b.id]:n});}} aria-label={`查看第 ${n+1} 张海报`}/>)}</div></>:<>

 {b.type==='video'?(b.video?<video src={b.video} poster={b.items[0].image||undefined} controls style={{height:b.height/2}}/>:<div className="video-empty" style={{height:b.height/2}}><Film/><span>活动现场 / 工厂影像</span><small>上传视频后在此播放</small></div>):b.type==='products'?<div className="product-cards">{b.items.map(i=>{const p=catalog.find(p=>p.sku===i.sku),price=i.price??p?.price,original=i.originalPrice??p?.originalPrice;return <div className="product-card" key={i.id}><Media src={i.image||p?.image||''}/><strong>{i.title||p?.name}</strong><div className="product-purchase"><div><b>{price!==undefined?'¥'+price.toFixed(2):'待选商品'}</b>{original!==undefined&&price!==undefined&&original>price&&<del>原价 ¥{original.toFixed(2)}</del>}</div><button type="button" aria-label="购物车效果预览" onClick={()=>window.alert('这里是页面预览，请在开发版小程序中加入购物车。')}>＋购物车</button></div></div>;})}</div>:b.type==='links'?<div className={`preview-grid ${b.columns===4?'four-entries':''} ${b.id==='default-community'?'community-entries':''}`} style={{gridTemplateColumns:`repeat(${b.columns},minmax(0,1fr))`}}>{b.items.map(i=><div key={i.id} className="preview-item">{(b.columns===4||i.image)&&<Media src={i.image} style={{height:b.height/2,aspectRatio:'auto'}}/>}<strong>{i.title} {b.columns!==4&&i.target!==0&&<span>↗</span>}</strong>{i.subtitle&&b.id!=='default-community'&&<p>{i.subtitle}</p>}</div>)}</div>:b.items.map(i=><div key={i.id}><Media src={i.image} className="poster-media" style={{height:b.height/2}}/>{i.title&&<p className="poster-title">{i.title} {i.target!==0?'↗':''}</p>}{i.subtitle&&<p>{i.subtitle}</p>}</div>)}
 </>}</section>;})}{!config.blocks.some(b=>b.visible)&&<div className="preview-empty">添加模块或打开显示开关</div>}<div className="phone-end">TOPUYI · 让热爱发光</div></div><div className="phone-tabs">{['首页','全部商品','个人中心'].map((v,i)=><span key={v} className={!i?'tab-on':''}><span>{['⌂','▣','○'][i]}</span>{v}</span>)}</div></div>;
}
export default function Home({online=false,userName='',onLogout}:{online?:boolean;userName?:string;onLogout?:()=>void}){
 const [catalog,setCatalog]=useState<Product[]>([]);
 useEffect(()=>{if(online)void ops('catalog').then(v=>setCatalog(v.products)).catch(()=>setNotice('商品列表暂未读取成功，请刷新重试。'));},[online]);
 const revisions=useRef<Record<string,string|null>>({draft:null,templates:null});
 const [config,setConfig]=useState<Config>(defaults),[selected,setSelected]=useState('default-banner');
 const [ready,setReady]=useState(false),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[saved,setSaved]=useState('尚未保存');
 const [uploadState,setUploadState]=useState<Record<string,string>>({});
 const [dialog,setDialog]=useState<'add'|'preview'|'templates'|'cloud'|'publish'|'content'|'products'|'product-detail'|null>(null),[templates,setTemplates]=useState<SavedTemplate[]>([]),[templateName,setTemplateName]=useState('');
 const [contentPreview,setContentPreview]=useState<Item|null>(null);
 const [detailItemId,setDetailItemId]=useState('');
 const [confirm,setConfirm]=useState<{title:string;action:()=>void}|null>(null);
 const [past,setPast]=useState<Config[]>([]),[future,setFuture]=useState<Config[]>([]);const drag=useRef(''),importRef=useRef<HTMLInputElement>(null),cfgRef=useRef(config);useEffect(()=>{cfgRef.current=config;},[config]);
 const [cloudLink,setCloudLink]=useState({accessCode:'',revision:null as string|null,updatedAt:''}),[cloudConnected,setCloudConnected]=useState(false);
 useEffect(()=>{if(!online)void readRecord<{accessCode:string;revision:string|null;updatedAt:string}>('cloud-preview-link').then(v=>{if(v)setCloudLink(v);}).catch(()=>{});},[online]);
 const [publication,setPublication]=useState({revision:null as string|null,updatedAt:'',productCount:0}),[publishReady,setPublishReady]=useState(false);
 async function openPublish(){setDialog('publish');setPublishReady(false);setBusy(true);try{const value=await ops('publishStatus');setPublication({revision:value.revision,updatedAt:value.updatedAt,productCount:value.productCount});setPublishReady(true);}catch(error){setNotice(error instanceof Error?error.message:'无法读取发布状态，请重试。');}finally{setBusy(false);}}
 async function publishCurrent(){if(dirty||!publishReady||busy)return;setBusy(true);try{const value=await ops('publish',{expectedRevision:publication.revision,expectedDraftRevision:revisions.current.draft});setPublication({revision:value.revision,updatedAt:value.updatedAt,productCount:value.productCount});setNotice('商城内容已发布。已接入正式商城的体验版、审核版和正式版打开或下拉刷新即可看到。');}catch(error){setPublishReady(false);setNotice(error instanceof Error?error.message:'发布失败，请重新检查后重试。');}finally{setBusy(false);}}
 const block=config.blocks.find(b=>b.id===selected),index=config.blocks.findIndex(b=>b.id===selected);
 useEffect(()=>{let alive=true;void (async()=>{try{if(online){const data=await ops('load');if(!alive)return;revisions.current={draft:data.draft?.revision||null,templates:data.templates?.revision||null};if(data.draft){const c=validateConfig(data.draft.config);setConfig(c);setSelected(c.blocks[0]?.id||'');setSaved(new Date(data.draft.updatedAt).toLocaleString('zh-CN')+' · '+data.draft.updatedBy);}setTemplates(data.templates?.items||[]);if(data.link)setCloudLink(data.link);}else{const stored=await readRecord<{config:Config;date:string}>('draft'),list=await readRecord<SavedTemplate[]>('templates');if(!alive)return;if(stored){const c=validateConfig(stored.config);setConfig(c);setSelected(c.blocks[0]?.id||'');setSaved(stored.date);}if(list)setTemplates(list);}if(alive)setReady(true);}catch(e){if(alive)setNotice(e instanceof Error?e.message:'草稿读取失败，请刷新重试。');}})();return()=>{alive=false;};},[online]);
 useEffect(()=>{if(!dirty)return;const h=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener('beforeunload',h);return()=>window.removeEventListener('beforeunload',h);},[dirty]);
 function change(next:Config){setPast(v=>[...v.slice(-19),cfgRef.current]);setFuture([]);setConfig(next);cfgRef.current=next;setDirty(true);}
 function update(patch:Partial<Block>){if(block)change({...config,blocks:config.blocks.map(b=>b.id===block.id?{...b,...patch}:b)});}
 function editItem(id:string,patch:Partial<Item>){if(block)update({items:block.items.map(i=>i.id===id?{...i,...patch}:i)});}
 function editDetailItem(patch:Partial<Item>){const latest=cfgRef.current;change({...latest,blocks:latest.blocks.map(b=>({...b,items:b.items.map(i=>i.id===detailItemId?{...i,...patch}:i)}))});}
 async function uploadDetail(files:FileList|null){if(!files||!detailItemId)return;const chosen=Array.from(files).slice(0,10);if(chosen.some(file=>!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024)){setNotice('详情主图仅支持 JPG、PNG、WebP，每张最大 8MB。');return;}setBusy(true);try{const urls=[];for(const file of chosen)urls.push(online?await uploadMedia(file):await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>typeof r.result==='string'?resolve(r.result):reject(new Error('Invalid file'));r.onerror=reject;r.readAsDataURL(file);}));const item=cfgRef.current.blocks.flatMap(b=>b.items).find(i=>i.id===detailItemId),next=[...(item?.detailImages||[]),...urls].slice(0,10);editDetailItem({detailImages:next});setNotice('商品详情主图已添加，请保存草稿。');}catch(e){setNotice(e instanceof Error?e.message:'详情主图上传失败。');}finally{setBusy(false);}}
 async function uploadDetailBlock(file:File|undefined,id:string){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024){setNotice('详情图片仅支持 JPG、PNG、WebP，最大 8MB。');return;}setBusy(true);try{const src=online?await uploadMedia(file):await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>typeof r.result==='string'?resolve(r.result):reject(new Error('Invalid file'));r.onerror=reject;r.readAsDataURL(file);}),item=cfgRef.current.blocks.flatMap(b=>b.items).find(i=>i.id===detailItemId);editDetailItem({detailBlocks:(item?.detailBlocks||[]).map(x=>x.id===id?{...x,image:src}:x)});setNotice('详情图片已上传，请保存草稿。');}catch(e){setNotice(e instanceof Error?e.message:'详情图片上传失败。');}finally{setBusy(false);}}
 function reorder(id:string,to:number){const a=[...config.blocks],from=a.findIndex(b=>b.id===id);if(from<0||to<0||to>=a.length||from===to)return;a.splice(to,0,a.splice(from,1)[0]);change({...config,blocks:a});}
 function undo(redo=false){const source=redo?future:past,v=source.at(-1);if(!v)return;if(redo){setFuture(source.slice(0,-1));setPast([...past,config]);}else{setPast(source.slice(0,-1));setFuture([...future,config]);}setConfig(v);cfgRef.current=v;setDirty(true);if(!v.blocks.some(b=>b.id===selected))setSelected(v.blocks[0]?.id||'');}
 async function persist(key:string,value:unknown){if(!online){await writeRecord(key,value);return;}if(key==='cloud-preview-link')return;const data=key==='draft'?await ops('save',{config:(value as {config:Config}).config,expectedRevision:revisions.current.draft}):await ops('templates',{templates:value,expectedRevision:revisions.current.templates});revisions.current[key]=data.record.revision;}
 async function save(){setBusy(true);try{const date=new Date().toLocaleString('zh-CN');await persist('draft',{config,date});setSaved(date+(online?' · '+userName:''));setDirty(false);setNotice(online?'共享草稿已保存，同事登录后可以继续编辑。':'草稿已保存到当前浏览器，图片和视频会一起保留。');return true;}catch(e){setNotice(e instanceof Error?e.message:'保存失败，请重试。');return false;}finally{setBusy(false);}}
 async function upload(file:File|undefined,itemId:string,video=false){if(!file||!block)return;const key=video?'video':itemId;if(!(video?['video/mp4','video/webm']:['image/jpeg','image/png','image/webp']).includes(file.type)){const message=video?'请选择 MP4 或 WebM 视频。':'请选择 JPG、PNG 或 WebP 图片。';setUploadState(v=>({...v,[key]:message}));setNotice(message);return;}if(file.size>(video?30:8)*1024*1024){const message=video?'视频请控制在 30MB 内。':'图片请控制在 8MB 内。';setUploadState(v=>({...v,[key]:message}));setNotice(message);return;}const blockId=block.id;setUploadState(v=>({...v,[key]:'正在上传，请稍候…'}));setBusy(true);try{const data=online?await uploadMedia(file):await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>typeof r.result==='string'?resolve(r.result):reject(new Error('Invalid file'));r.onerror=reject;r.readAsDataURL(file);});if(!online&&!video)await new Promise<void>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve();img.onerror=reject;img.src=data;});const latest=cfgRef.current;change({...latest,blocks:latest.blocks.map(b=>b.id!==blockId?b:video?{...b,video:data}:{...b,items:b.items.map(i=>i.id===itemId?{...i,image:data,filename:file.name}:i)})});setUploadState(v=>({...v,[key]:'上传成功，请保存草稿'}));setNotice(`${file.name} 已添加，保存草稿后保留。`);}catch(e){const message=e instanceof Error?e.message:'文件读取失败，请检查文件后重试。';setUploadState(v=>({...v,[key]:message}));setNotice(message);}finally{setBusy(false);}}
 function exportTemplate(){const blob=new Blob([JSON.stringify(config)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`TOPUYI-首页模板-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice(online?'已导出配置备份，素材引用限本运营后台使用。':'已导出模板，包含图片和视频。同事可以在装修后台导入。');}
 async function importTemplate(file?:File){if(!file)return;if(file.size>100*1024*1024){setNotice('模板文件不能超过 100MB。');return;}try{const parsed=validateConfig(JSON.parse(await file.text()));const c=online?await migrateMedia(parsed):parsed;setConfirm({title:'用导入模板替换当前页面？可通过撤销恢复。',action:()=>{change(c);setSelected(c.blocks[0]?.id||'');setNotice('模板已导入，请保存草稿。');}});}catch{setNotice('模板格式不正确，请选择从本后台导出的 JSON 文件。');}}
 async function storeTemplate(){if(!templateName.trim())return;if(online&&templates.length>=20){setNotice('最多保存 20 个模板。');return;}const next=[{id:crypto.randomUUID(),name:templateName.trim(),date:new Date().toLocaleString('zh-CN'),config},...templates];setBusy(true);try{await persist('templates',next);setTemplates(next);setTemplateName('');setNotice('已存为模板。');}catch(e){setNotice(e instanceof Error?e.message:'模板保存失败。');}finally{setBusy(false);}}
 async function checkCloud(){setBusy(true);setCloudConnected(false);try{if(online){const value=await ops('status');setCloudLink(v=>({...v,...value}));setCloudConnected(true);setNotice('连接正常，可以同步到开发版。');return;}const r=await fetch('/api/home-preview/status',{headers:{'x-topuyi-preview':'1'}});const value=await r.json() as {error?:string;revision:string;updatedAt:string;accessCode:string};if(!r.ok)throw new Error(value.error);setCloudLink(v=>({...v,revision:value.revision,updatedAt:value.updatedAt||''}));setCloudConnected(true);setNotice('云开发连接正常，可以同步到开发版。');}catch(e){setNotice(e instanceof Error?e.message:'连接失败，请检查云开发登录。');}finally{setBusy(false);}}
 async function syncCloud(){if(!cloudConnected)return;setBusy(true);try{if(online){const value=await ops('sync',{config,expectedRevision:cloudLink.revision});setCloudLink({accessCode:value.accessCode,revision:value.revision,updatedAt:value.updatedAt});setNotice('已同步到开发版。开发版首页下拉刷新即可。');return;}const r=await fetch('/api/home-preview/sync',{method:'POST',headers:{'content-type':'application/json','x-topuyi-preview':'1'},body:JSON.stringify({config,accessCode:cloudLink.accessCode,expectedRevision:cloudLink.revision})});const value=await r.json() as {error?:string;revision:string;updatedAt:string;accessCode:string};if(!r.ok)throw new Error(value.error);const link={accessCode:value.accessCode,revision:value.revision,updatedAt:value.updatedAt};setCloudLink(link);try{await writeRecord('cloud-preview-link',link);}catch{setNotice('已同步，但本机存储失败，请复制预览码保留。');return;}setNotice('已同步到开发版。首次请在开发版首页输入预览码；之后下拉刷新即可。');}catch(e){setNotice(e instanceof Error?e.message:'同步失败，本地草稿已保留。');}finally{setBusy(false);}}
 async function copyCode(){try{await navigator.clipboard.writeText(cloudLink.accessCode);setNotice('预览码已复制，在开发版首页点击“连接电脑后台”后粘贴。');}catch{setNotice('无法自动复制，请选中预览码手动复制。');}}
 const actionRef=useRef({save,ready,busy});useEffect(()=>{actionRef.current={save,ready,busy};});
 useEffect(()=>{
  type Tool={name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown};
  const context=(document as Document & {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(online||!context?.registerTool)return;const lifecycle=new AbortController();
  const tools:Tool[]=[
   {name:'read_home_draft_modules',description:'Read the current local homepage module order and visibility. Does not include image or video data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({modules:cfgRef.current.blocks.map(({id,title,type,visible})=>({id,title,type,visible}))})},
   {name:'save_local_home_draft',description:'Save the currently edited homepage and media in this browser only. Does not publish to the mini program.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');if(!actionRef.current.ready||actionRef.current.busy)throw new Error('Editor not ready');if(!await actionRef.current.save())throw new Error('Local storage failed');return {saved:true,scope:'current_browser'};}}
  ];
  for(const tool of tools){try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
  return()=>lifecycle.abort();
 },[online]);
 return <SidebarProvider style={{'--sidebar-width':'190px'} as CSSProperties}><Sidebar collapsible="offcanvas" className="brand-sidebar"><SidebarHeader><div className="logo">TOPUYI<span>商家运营工作台</span></div></SidebarHeader><SidebarContent><div className="nav-caption">店铺管理</div><SidebarMenu><SidebarMenuItem><SidebarMenuButton isActive><PanelsTopLeft/><span>首页装修</span></SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton onClick={()=>setDialog('templates')}><FolderOpen/><span>我的模板</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu><div className="sidebar-guide"><span>使用流程</span><p>01　选择页面模块</p><p>02　上传图片与视频</p><p>03　预览并保存草稿</p></div></SidebarContent><SidebarFooter><div className="local-badge"><Monitor size={16}/>{online?'共享工作空间':'本机工作空间'}</div><p className="local-note">仅连接开发版首页</p>{online&&<><p className="local-note">{userName}</p><Button variant="outline" onClick={()=>dirty?setConfirm({title:"有未保存的修改，确定退出登录？",action:()=>onLogout?.()}):onLogout?.()}>退出登录</Button></>}</SidebarFooter></Sidebar>
 <main className="workspace"><header className="topbar"><div className="crumb"><SidebarTrigger/><span>店铺装修</span><ChevronRight size={15}/><b>首页</b></div><div className="top-actions">{online&&<Button onClick={openPublish} disabled={!ready||busy}><Upload/>发布商城</Button>}<Button onClick={()=>setDialog('cloud')} disabled={!ready||busy}><Upload/>同步到开发版</Button><Button variant="outline" onClick={()=>importRef.current?.click()} disabled={!ready||busy}><Upload/>导入模板</Button><Button variant="outline" onClick={exportTemplate} disabled={!ready||busy}><Download/>导出模板</Button><Button variant="outline" onClick={()=>setDialog('preview')}><Eye/>预览</Button><Button onClick={save} disabled={!ready||busy}><Save/>{busy?'处理中…':online?'保存共享草稿':'保存草稿'}</Button></div></header>
 <div className="page-heading"><div><div className="title-line"><h1>首页装修</h1><span className="draft-tag">{dirty?'有未保存修改':'草稿'}</span></div><p>上传素材，自由组合你的品牌首页。</p></div><div className="save-state"><Check size={15}/>{ready?saved:'正在读取草稿…'}</div></div><div className="scope-note"><Monitor size={16}/><span>{online?'先保存共享草稿，再发布商城供客户和审核人员查看；同步到开发版用于单独测试。':'保存草稿保留在本机；同步到开发版上传独立首页配置和素材。'}</span></div>{notice&&<output className="feedback"><span>{notice}</span><button aria-label="关闭提示" onClick={()=>setNotice('')}><X size={16}/></button></output>}
 <div className="editor-grid" aria-busy={busy||!ready}><aside className="module-panel"><div className="panel-header"><b>页面模块</b><span>{config.blocks.length} 个</span></div><p className="panel-help">拖动排序，点击编辑</p><div className="module-rows">{config.blocks.map((b,n)=>{const Icon=icons[b.type];return <div key={b.id} draggable={!busy&&ready} onDragStart={()=>{drag.current=b.id;}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();reorder(drag.current,n);drag.current='';}} className={`module-row ${b.id===selected?'active':''}`}><button className="module-select" disabled={busy||!ready} onClick={()=>setSelected(b.id)}><GripVertical className="grip" size={16}/><Icon size={19}/><span><b>{b.title||kinds[b.type]}</b><small>{kinds[b.type]}</small></span></button><button aria-label={b.visible?'隐藏模块':'显示模块'} disabled={busy||!ready} onClick={()=>change({...config,blocks:config.blocks.map(v=>v.id===b.id?{...v,visible:!v.visible}:v)})}>{b.visible?<Eye size={15}/>:<EyeOff size={15}/>}</button></div>;})}</div><Button variant="outline" className="add-module" onClick={()=>setDialog('add')} disabled={!ready||busy||config.blocks.length>=30}><Plus/>添加模块</Button><div className="module-bottom"><span>最多 30 个模块</span><div><Button variant="ghost" size="icon" aria-label="撤销" disabled={!past.length||busy} onClick={()=>undo()}><Undo2/></Button><Button variant="ghost" size="icon" aria-label="重做" disabled={!future.length||busy} onClick={()=>undo(true)}><Redo2/></Button></div></div></aside>
 <section className="canvas"><div className="canvas-heading"><span><Smartphone size={16}/>手机实时预览</span><small>375 px</small></div><Preview catalog={catalog} config={config} selected={selected} onSelect={setSelected}/><p className="canvas-tip">点击预览中的模块，编辑对应内容</p></section>
 <aside className="properties"><div className="panel-header"><b>{block?kinds[block.type]:'模块设置'}</b><span>编辑设置</span></div>{block?<fieldset disabled={busy||!ready}><Tabs defaultValue="content"><TabsList variant="line" className="editor-tabs"><TabsTrigger value="content">内容设置</TabsTrigger><TabsTrigger value="style">样式设置</TabsTrigger></TabsList><TabsContent value="content"><div className="field-body"><div className="field switch-field"><span>在图片／视频上方显示标题和介绍</span><Switch checked={block.showHeading!==false} onCheckedChange={v=>update({showHeading:v})} aria-label="在图片／视频上方显示标题和介绍"/></div><Field title="模块标题"><Input maxLength={60} value={block.title} onChange={e=>update({title:e.target.value})}/></Field><Field title="介绍文字"><textarea maxLength={300} value={block.subtitle} onChange={e=>update({subtitle:e.target.value})}/></Field><div className="field switch-field"><span>显示该模块</span><Switch checked={block.visible} onCheckedChange={v=>update({visible:v})} aria-label="显示该模块"/></div>
 {block.items.some(i=>i.target===1)&&<Button type="button" className="wide" onClick={()=>setDialog('products')}><Eye/>进入所有商品子页面</Button>}
 {block.type==='video'&&<div className="media-editor"><b>视频</b><label className="upload-zone"><Film/><strong>{block.video?'替换视频':'点击上传视频'}</strong><span>MP4 / WebM，最大 30MB</span><input type="file" accept="video/mp4,video/webm" onChange={e=>{void upload(e.target.files?.[0],'',true);e.target.value='';}}/></label>{block.video&&<Button variant="outline" onClick={()=>update({video:''})}>移除视频</Button>}</div>}
 <div className="section-label">{block.type==='video'?'视频封面':'内容与图片'}<span>{block.items.length} 项</span></div>{block.items.map((i,n)=><div className="item-editor" key={i.id}><div className="item-top"><b>{block.type==='banner'?'轮播图':'内容'} {n+1}</b><div><Button variant="ghost" size="icon-sm" aria-label="内容上移" disabled={!n} onClick={()=>{const a=[...block.items];[a[n-1],a[n]]=[a[n],a[n-1]];update({items:a});}}><ArrowUp/></Button><Button variant="ghost" size="icon-sm" aria-label="删除内容" disabled={block.items.length<=1} onClick={()=>setConfirm({title:'删除这项内容和对应图片？',action:()=>update({items:block.items.filter(v=>v.id!==i.id)})})}><Trash2/></Button></div></div>
 <label className={`upload-zone ${i.image?'has-image':''}`}>{i.image?<img src={i.image} alt={i.title}/>:<ImagePlus/>}<strong>{uploadState[i.id]||(i.image?'点击替换图片':'点击或拖入图片')}</strong><span>JPG / PNG / WebP，最大 8MB</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{void upload(e.target.files?.[0],i.id);e.target.value='';}}/></label>{i.image&&<div className="file-caption"><span>{i.filename||'模板图片'}</span><button onClick={()=>editItem(i.id,{image:'',filename:''})}>移除</button></div>}
 <>{block.type==='products'&&<p className="text-sm text-slate-500">保存后发布商城，商品即可展示和购买。暂不管理库存；请填写商品标题、图片及销售价格。</p>}{block.type==='products'&&<><Field title="商品分类"><Input maxLength={20} placeholder="例如：荧光棒" value={i.category||'荧光棒'} onChange={e=>editItem(i.id,{category:e.target.value})}/></Field><Field title="销售价格（元）"><Input type="number" min="0" step="0.01" value={i.price??catalog.find(p=>p.sku===i.sku)?.price??0} onChange={e=>editItem(i.id,{price:Math.max(0,Number(e.target.value)||0)})}/></Field><Field title="原价（元）"><Input type="number" min="0" step="0.01" value={i.originalPrice??catalog.find(p=>p.sku===i.sku)?.originalPrice??0} onChange={e=>editItem(i.id,{originalPrice:Math.max(0,Number(e.target.value)||0)})}/></Field></>}</><Field title="标题"><Input maxLength={80} value={i.title} onChange={e=>editItem(i.id,{title:e.target.value})}/></Field><Field title={block.type==='products'?'商品详情':block.id==='default-community'?'内容页文字':'说明'}>{block.id==='default-community'?<textarea maxLength={3000} value={i.subtitle} onChange={e=>editItem(i.id,{subtitle:e.target.value})}/>:<Input maxLength={200} value={i.subtitle} onChange={e=>editItem(i.id,{subtitle:e.target.value})}/>}</Field>{block.type==='products'&&<Button type="button" variant="outline" className="wide" onClick={()=>{setDetailItemId(i.id);setDialog('product-detail');}}><Eye/>编辑商品详情页</Button>}{block.id==='default-community'&&<Button type="button" variant="outline" className="wide" onClick={()=>{setContentPreview(i);setDialog('content');}}><Eye/>进入子页面预览</Button>}{i.target===1&&block.type!=='products'&&<Button type="button" variant="outline" className="wide" onClick={()=>setDialog('products')}><Eye/>进入全部商品页预览</Button>}<Field title="点击跳转"><Choice value={targets[i.target]} values={targets} onChange={v=>editItem(i.id,{target:targets.indexOf(v)})}/></Field></div>)}{block.type!=='video'&&<Button variant="outline" className="wide" disabled={block.items.length>=20} onClick={()=>update({items:[...block.items,newItem('新内容')]})}><Plus/>添加内容项</Button>}</div></TabsContent>
 <TabsContent value="style"><div className="field-body"><Field title="背景颜色"><div className="colors">{colors.map(c=><button key={c} style={{background:c}} className={block.background===c?'chosen':''} aria-label={'背景色 '+c} onClick={()=>update({background:c})}>{block.background===c&&<Check size={15}/>}</button>)}</div></Field><Field title={`${block.columns===4&&['links','products'].includes(block.type)?'四张图片统一高度':'媒体高度'} · ${block.height} rpx`}><Slider min={160} max={900} step={20} value={[block.height]} onValueChange={v=>update({height:Array.isArray(v)?v[0]:v})}/></Field><Field title={`模块间距 · ${block.spacing} px`}><Slider min={0} max={40} step={2} value={[block.spacing]} onValueChange={v=>update({spacing:Array.isArray(v)?v[0]:v})}/></Field>{['products','links'].includes(block.type)&&<Field title="排列方式"><Choice value={block.columns===1?'单列':block.columns===4?'四列':'双列'} values={['单列','双列','四列']} onChange={v=>update({columns:v==='单列'?1:v==='四列'?4:2})}/></Field>}</div></TabsContent></Tabs>
 <div className="block-actions"><Button variant="outline" disabled={index===0} onClick={()=>reorder(block.id,index-1)}><ArrowUp/>上移</Button><Button variant="outline" disabled={index===config.blocks.length-1} onClick={()=>reorder(block.id,index+1)}><ArrowDown/>下移</Button><Button variant="outline" disabled={config.blocks.length>=30} onClick={()=>{const b={...structuredClone(block),id:crypto.randomUUID(),items:block.items.map(i=>({...i,id:crypto.randomUUID()}))},a=[...config.blocks];a.splice(index+1,0,b);change({...config,blocks:a});setSelected(b.id);}}><Copy/>复制</Button><Button variant="outline" onClick={()=>setConfirm({title:'删除整个模块？可以通过撤销恢复。',action:()=>{change({...config,blocks:config.blocks.filter(b=>b.id!==block.id)});setSelected(config.blocks.find(b=>b.id!==block.id)?.id||'');}})}><Trash2/>删除</Button></div></fieldset>:<div className="no-selection">添加一个模块，开始装修首页。</div>}</aside></div>
 <input hidden ref={importRef} type="file" accept=".json,application/json" onChange={e=>{void importTemplate(e.target.files?.[0]);e.target.value='';}}/></main>
 <Dialog open={dialog!==null} onOpenChange={v=>!v&&setDialog(null)}><DialogContent className={dialog==='product-detail'?'product-detail-dialog':dialog==='preview'||dialog==='products'?'preview-dialog':'admin-dialog'}><DialogTitle>{dialog==='add'?'添加页面模块':dialog==='templates'?'我的模板':dialog==='cloud'?'同步到开发版':dialog==='publish'?'发布商城':dialog==='content'?'子页面预览':dialog==='products'?'全部商品页预览':dialog==='product-detail'?'编辑商品详情页':'首页预览'}</DialogTitle><DialogDescription>{dialog==='publish'?'发布已保存的共享草稿。体验版、审核版和正式版使用同一份已发布内容，客户无需输入预览码。':dialog==='cloud'?'配置和素材写入独立的首页预览区域，不会发布微信新版小程序。':dialog==='preview'?'预览当前编辑内容，跳转仅为展示。':dialog==='products'?'商品顺序和分类来自“发现好物”模块，可由运营人员调整。':dialog==='product-detail'?'可调整标题、详情文字和最多 10 张轮播主图。':dialog==='content'?'这里显示该入口点击后打开的独立页面。':dialog==='templates'?(online?'团队共享模板，保存后同事可直接使用。':'模板保存在当前浏览器，也可导出给同事使用。'):'选择模块加入页面，之后可以自由调整顺序。'}</DialogDescription>
 {dialog==='publish'&&<div className="cloud-panel">{notice&&<output className="cloud-feedback">{notice}</output>}<p>本次共享草稿：{config.blocks.filter(b=>b.visible).length} 个模块，{config.blocks.filter(b=>b.visible&&b.type==='products').reduce((n,b)=>n+b.items.length,0)} 个商品</p><p>{dirty?'还有未保存修改，请先关闭窗口并保存共享草稿。':'将以上已保存的商品、图片、售价和页面内容发布给商城用户。'}</p><small>首次接入需要上传新版小程序；之后更换图片、上新及修改售价，保存并发布商城即可。发布草稿不会替你提交微信审核。</small><p>最近发布：{publication.updatedAt?new Date(publication.updatedAt).toLocaleString('zh-CN'):'尚未发布'}</p><div className="flex gap-3"><Button variant="outline" onClick={openPublish} disabled={busy}>重新检查</Button><Button onClick={publishCurrent} disabled={!publishReady||dirty||busy||!revisions.current.draft}>{busy?'处理中…':'发布这份共享草稿'}</Button></div></div>}
 {dialog==='cloud'&&<div className="cloud-panel">{notice&&<output className="cloud-feedback">{notice}</output>}<p>1. 检查云开发连接</p><Button variant="outline" onClick={checkCloud} disabled={busy}>{busy?'处理中…':cloudConnected?'重新检查连接':'检查连接'}</Button><p>2. 将当前页面同步到开发版</p><Button onClick={syncCloud} disabled={!cloudConnected||busy}>{busy?'处理中…':'同步当前页面'}</Button><small>会替换云端开发版预览，正式商城不变。素材较大时请等待同步完成。</small>{cloudLink.accessCode&&<><p>3. 开发版首页 → 连接电脑后台 → 粘贴预览码</p><div className="code-copy"><Input readOnly aria-label="开发版预览码" value={cloudLink.accessCode}/><Button variant="outline" onClick={copyCode}>复制</Button></div><small>预览码仅用于读取这套开发版首页，请只发给参与预览的同事。</small><p className="cloud-date">最近同步：{cloudLink.updatedAt?new Date(cloudLink.updatedAt).toLocaleString('zh-CN'):'暂无'}</p></>}<p>以后每次同步后，在开发版首页下拉刷新即可。</p></div>}
 {dialog==='content'&&contentPreview&&<div className="mx-auto mt-2 max-w-[390px] overflow-hidden rounded-[18px] bg-[#f5f5f7] shadow-lg">{contentPreview.image?<img className="block max-h-[430px] w-full bg-white object-contain" src={contentPreview.image} alt={contentPreview.title}/>:<div className="flex h-[220px] items-center justify-center bg-[#edf0f4] text-[#9aa5b4]">暂无图片</div>}<article className="m-3 rounded-xl bg-white p-5"><h2 className="mb-4 text-[22px] leading-[1.45] font-bold">{contentPreview.title}</h2><p className="whitespace-pre-wrap break-words text-[15px] leading-[1.8] text-[#566174]">{contentPreview.subtitle||'暂无内容'}</p></article></div>}
 {dialog==='products'&&(()=>{const productBlock=config.blocks.find(b=>b.type==='products'),items=productBlock?.items||[],categories=[...new Set(items.map(i=>i.category||'荧光棒'))];return <div className="mx-auto mt-2 flex h-[680px] w-full max-w-[390px] flex-col overflow-hidden rounded-[18px] bg-[#f6f7f8] shadow-lg"><div className="bg-white p-4 text-center text-xl font-bold">全部商品</div><div className="m-3 rounded-full bg-white px-4 py-3 text-sm text-slate-400">搜索商品</div><div className="flex min-h-0 flex-1"><div className="w-[92px] bg-[#f0f1f3]">{categories.map((c,n)=><div key={c} className={`px-3 py-4 text-sm ${n===0?'bg-white font-bold':''}`}>{c}</div>)}</div><div className="flex-1 space-y-3 overflow-y-auto bg-white p-3">{items.map(i=>{const p=catalog.find(p=>p.sku===i.sku);return <div key={i.id} className="flex gap-3 border-b pb-3"><Media src={i.image||p?.image||''} className="h-24 w-24 shrink-0 rounded-lg object-cover"/><div className="min-w-0 flex-1"><b className="line-clamp-2 text-sm">{i.title||p?.name}</b><p className="mt-2 text-xs text-pink-500">{i.category||'荧光棒'}</p><strong className="mt-2 block text-lg text-rose-500">{i.price!==undefined?'¥'+i.price.toFixed(2):p?'¥'+p.price.toFixed(2):'待填写价格'}</strong></div></div>;})}</div></div></div>;})()}
 {dialog==='product-detail'&&(()=>{const i=config.blocks.flatMap(b=>b.items).find(v=>v.id===detailItemId);if(!i)return null;const p=catalog.find(p=>p.sku===i.sku),images=i.detailImages||[];return <div className="grid gap-5 md:grid-cols-[minmax(0,1fr)_390px]"><div className="space-y-4"><Field title="商品标题"><Input maxLength={80} value={i.title} onChange={e=>editDetailItem({title:e.target.value})}/></Field><Field title="商品详情文字"><textarea className="min-h-40" maxLength={200} value={i.subtitle} onChange={e=>editDetailItem({subtitle:e.target.value})}/></Field><div className="section-label">详情页轮播主图<span>{images.length}/10 张</span></div><label className="upload-zone"><ImagePlus/><strong>上传多张主图</strong><span>可一次选择多张，JPG / PNG / WebP，每张最大 8MB</span><input multiple type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{void uploadDetail(e.target.files);e.target.value='';}}/></label><div className="grid grid-cols-2 gap-3">{images.map((src,n)=><div key={src+n} className="rounded-lg border p-2"><img className="h-32 w-full rounded object-cover" src={src} alt={`主图 ${n+1}`}/><div className="mt-2 flex justify-between"><Button size="sm" variant="ghost" disabled={!n} onClick={()=>{const a=[...images];[a[n-1],a[n]]=[a[n],a[n-1]];editDetailItem({detailImages:a});}}>上移</Button><Button size="sm" variant="ghost" onClick={()=>editDetailItem({detailImages:images.filter((_,x)=>x!==n)})}>删除</Button></div></div>)}</div></div><div className="overflow-hidden rounded-[18px] bg-[#f5f5f7] shadow-lg"><div className="flex snap-x overflow-x-auto">{(images.length?images:[i.image||p?.image||'']).map((src,n)=><div key={n} className="w-full shrink-0 snap-center"><Media src={src} className="h-[360px] w-full bg-white object-contain"/></div>)}</div><article className="m-3 rounded-xl bg-white p-5"><h2 className="mb-3 text-[22px] font-bold">{i.title||p?.name}</h2>{(i.price!==undefined||p)&&<b className="text-xl text-rose-500">¥{(i.price??p?.price??0).toFixed(2)}</b>}<h3 className="mt-6 mb-2 font-bold">商品详情</h3><p className="whitespace-pre-wrap text-sm leading-7 text-slate-600">{i.subtitle||'暂无商品详情'}</p></article><div className="sticky bottom-0 grid grid-cols-2 gap-2 bg-white p-3 shadow-[0_-4px_18px_rgba(0,0,0,.08)]"><Button type="button" variant="outline" className="rounded-full bg-amber-50">加入购物车</Button><Button type="button" className="rounded-full bg-[#ffd100] text-slate-900 hover:bg-[#f2c600]">立即购买</Button></div></div></div>;})()}
 {dialog==='product-detail'&&(()=>{const i=config.blocks.flatMap(b=>b.items).find(v=>v.id===detailItemId);if(!i)return null;const rows=i.detailBlocks||[];return <section className="mt-5 rounded-xl bg-white p-5"><div className="section-label">详情图文混排<span>{rows.length}/30 项</span></div><p className="mb-4 text-sm text-slate-500">按照这里的顺序在商品详情页显示。每项右上角可上移、下移或删除。</p><div className="space-y-3">{rows.map((x,n)=><div key={x.id} className="rounded-lg border p-3"><div className="mb-3 flex items-center justify-between"><b>{x.type==='text'?'文字':'图片'} {n+1}</b><div className="flex gap-1"><Button size="sm" variant="ghost" disabled={!n} onClick={()=>{const a=[...rows];[a[n-1],a[n]]=[a[n],a[n-1]];editDetailItem({detailBlocks:a});}}>上移</Button><Button size="sm" variant="ghost" disabled={n===rows.length-1} onClick={()=>{const a=[...rows];[a[n],a[n+1]]=[a[n+1],a[n]];editDetailItem({detailBlocks:a});}}>下移</Button><Button size="sm" variant="ghost" onClick={()=>editDetailItem({detailBlocks:rows.filter(v=>v.id!==x.id)})}>删除</Button></div></div>{x.type==='text'?<textarea className="min-h-28 w-full rounded border p-3" maxLength={3000} placeholder="输入商品介绍、规格说明等" value={x.text||''} onChange={e=>editDetailItem({detailBlocks:rows.map(v=>v.id===x.id?{...v,text:e.target.value}:v)})}/>:<label className={`upload-zone ${x.image?'has-image':''}`}>{x.image?<img src={x.image} alt="详情图片"/>:<ImagePlus/>}<strong>{x.image?'点击替换图片':'点击上传详情图片'}</strong><span>JPG / PNG / WebP，最大 8MB</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{void uploadDetailBlock(e.target.files?.[0],x.id);e.target.value='';}}/></label>}</div>)}</div><div className="mt-4 grid grid-cols-2 gap-3"><Button type="button" variant="outline" disabled={rows.length>=30} onClick={()=>editDetailItem({detailBlocks:[...rows,{id:crypto.randomUUID(),type:'text',text:''}]})}><Plus/>添加文字</Button><Button type="button" variant="outline" disabled={rows.length>=30} onClick={()=>editDetailItem({detailBlocks:[...rows,{id:crypto.randomUUID(),type:'image',image:''}]})}><ImagePlus/>添加图片</Button></div></section>;})()}
 {dialog==='add'&&<div className="component-grid">{(Object.keys(kinds) as Kind[]).map(k=>{const Icon=icons[k];return <button key={k} onClick={()=>{const b=newBlock(k);change({...config,blocks:[...config.blocks,b]});setSelected(b.id);setDialog(null);}}><Icon/><b>{kinds[k]}</b><span>{{banner:'多张大图，左右切换',video:'活动现场与品牌影像',links:'图片入口，支持一排四个',poster:'产品活动与宣传海报',products:'商品图片与展示卡片',about:'公司历程与品牌故事'}[k]}</span></button>;})}</div>}
 {dialog==='preview'&&<Preview catalog={catalog} config={config} selected="" onSelect={()=>{}} interactive/>}
 {dialog==='templates'&&<div className="template-library"><div className="template-save"><Input placeholder="模板名称，例如：新品上新首页" maxLength={50} value={templateName} onChange={e=>setTemplateName(e.target.value)}/><Button onClick={storeTemplate} disabled={!templateName.trim()||busy||!ready}>存为模板</Button></div><button className="template-entry" onClick={()=>setConfirm({title:'恢复 Excel 参考默认模板？可通过撤销恢复。',action:()=>{const c=defaults();change(c);setSelected(c.blocks[0].id);setDialog(null);}})}><span><b>品牌首页 · 默认模板</b><small>轮播 / 视频 / 技术支持 / 商品 / 公司介绍</small></span><ChevronRight/></button>{templates.map(t=><div className="template-entry" key={t.id}><span><b>{t.name}</b><small>{t.date}</small></span><Button variant="outline" onClick={()=>setConfirm({title:`使用“${t.name}”替换当前页面？`,action:()=>{change(structuredClone(t.config));setSelected(t.config.blocks[0]?.id||'');setDialog(null);}})}>使用</Button><Button variant="ghost" size="icon" aria-label="删除模板" onClick={()=>setConfirm({title:`删除保存的模板“${t.name}”？`,action:()=>{const next=templates.filter(v=>v.id!==t.id);void persist('templates',next).then(()=>setTemplates(next)).catch(()=>setNotice('删除失败，请重试。'));}})}><Trash2/></Button></div>)}</div>}
 </DialogContent></Dialog><AlertDialog open={!!confirm} onOpenChange={v=>!v&&setConfirm(null)}><AlertDialogContent><AlertDialogTitle>确认操作</AlertDialogTitle><AlertDialogDescription>{confirm?.title}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={()=>{confirm?.action();setConfirm(null);}}>确认</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></SidebarProvider>;
}
