'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {ops} from '@/lib/ops-client';
import './member-redemptions.css';
type Stock={id:string;title:string;published:boolean;remaining:number|null;redeemed:number;revision:string|null;configured:boolean};
type Order={id:string;orderNo:string;status:string;product:{title:string;points:number};quantity:number;totalPoints:number;address:{name:string;phone:string;province:string;city:string;district:string;detail:string};shipping:{carrier:string;trackingNo:string}|null;createdAt:number;revision:string};
type Result={items:Stock[];orders:Order[];hasMore:boolean;order:Order;remaining:number|null;redeemed:number;revision:string};
const api=async(action:string,body?:unknown)=>await ops(action,body,{timeoutMs:30000}) as unknown as Result;
const labels:Record<string,string>={processing:'待发货',shipped:'已发货',completed:'已完成'};
export default function MemberRedemptions({onBack}:{onBack:()=>void}){
 const [tab,setTab]=useState<'stock'|'orders'>('stock'),[items,setItems]=useState<Stock[]>([]),[orders,setOrders]=useState<Order[]>([]),[values,setValues]=useState<Record<string,string>>({});
 const [status,setStatus]=useState(''),[offset,setOffset]=useState(0),[hasMore,setHasMore]=useState(false),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [selected,setSelected]=useState<Order|null>(null),[carrier,setCarrier]=useState(''),[trackingNo,setTrackingNo]=useState(''),[shippingError,setShippingError]=useState('');
 const sequence=useRef(0);
 async function load(){const n=++sequence.current;setLoading(true);setError('');try{const r=await api(tab==='stock'?'memberInventory':'memberRedemptionOrders',tab==='stock'?undefined:{status,offset});if(n!==sequence.current)return;if(tab==='stock'){setItems(r.items);setValues(Object.fromEntries(r.items.map(p=>[p.id,p.remaining===null?'':String(p.remaining)])));}else{setOrders(r.orders);setHasMore(r.hasMore);}}catch(e){if(n===sequence.current)setError(e instanceof Error?e.message:'读取失败，请重试。');}finally{if(n===sequence.current)setLoading(false);}}
 useEffect(()=>{void load();return()=>{sequence.current++;};},[tab,status,offset]);
 async function saveStock(p:Stock){const raw=(values[p.id]||'').trim(),remaining=raw===''?null:Number(raw);if(remaining!==null&&(!/^-?\d+$/.test(raw)||!Number.isSafeInteger(remaining)||Math.abs(remaining)>99999999)){setError('库存请留空或填写 -99999999–99999999 的整数。');return;}setBusy(true);setError('');setNotice('');try{const r=await api('memberSetStock',{productId:p.id,remaining,expectedRevision:p.revision});setItems(list=>list.map(x=>x.id===p.id?{...x,remaining:r.remaining,redeemed:r.redeemed,revision:r.revision,configured:r.remaining!==null}:x));setNotice('库存已保存，立即生效。');}catch(e){setError(e instanceof Error?e.message:'保存失败。');}finally{setBusy(false);}}
 async function ship(){if(!selected||busy)return;setBusy(true);setShippingError('');try{const r=await api('memberRedemptionShip',{orderId:selected.id,expectedRevision:selected.revision,carrier,trackingNo});setOrders(rows=>rows.map(o=>o.id===r.order.id?r.order:o));setSelected(null);setNotice('已记录发货，用户可在兑换订单中查看物流单号。');}catch(e){setShippingError(e instanceof Error?e.message:'发货保存失败。');}finally{setBusy(false);}}
 return <main className="redemption-admin"><header className="redemption-admin-header"><div><p>会员中心</p><h1>积分兑换管理</h1></div><Button variant="outline" disabled={busy} onClick={onBack}>返回会员中心装修</Button></header>
 <div className="redemption-toolbar"><div className="redemption-tabs"><Button variant={tab==='stock'?'default':'outline'} disabled={busy} onClick={()=>{setTab('stock');setNotice('');}}>商品库存</Button><Button variant={tab==='orders'?'default':'outline'} disabled={busy} onClick={()=>{setTab('orders');setNotice('');}}>兑换订单</Button></div><Button variant="outline" disabled={busy||loading} onClick={()=>void load()}>刷新</Button></div>
 {notice&&<output className="feedback" role="status">{notice}</output>}{error&&<div className="redemption-admin-error" role="alert">{error} 请点击“刷新”读取最新状态后重试。</div>}
 {tab==='stock'?<><p className="redemption-admin-help">先保存会员中心商品草稿，再设置库存。库存留空表示不限量兑换；填写整数后按剩余库存扣减，小于或等于 0 时显示库存不足。保存立即生效。</p>{loading?<p>正在读取库存…</p>:items.length?<div className="redemption-stock-list">{items.map(p=><article className="redemption-stock" key={p.id}><div><h2>{p.title}</h2><p>{p.published?'已发布':'草稿商品'} · 累计兑换 {p.redeemed} 件</p>{!p.configured&&<small>不限量兑换</small>}</div><label>剩余库存<Input type="number" placeholder="留空不限量" min={-99999999} max={99999999} step={1} aria-label={p.title+'剩余库存'} disabled={busy} value={values[p.id]??''} onChange={e=>setValues(v=>({...v,[p.id]:e.target.value}))}/></label><Button disabled={busy} onClick={()=>void saveStock(p)}>保存库存</Button></article>)}</div>:<p className="redemption-admin-empty">还没有积分商品，请先返回会员中心添加并保存草稿。</p>}</>:<><div className="redemption-toolbar"><label>订单状态 <select value={status} disabled={busy||loading} onChange={e=>{setStatus(e.target.value);setOffset(0);}}><option value="">全部</option>{Object.entries(labels).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><span>第 {Math.floor(offset/20)+1} 页</span></div>{loading?<p>正在读取兑换订单…</p>:orders.length?orders.map(o=><article className="redemption-order" key={o.id}><header><b>{o.orderNo}</b><span>{labels[o.status]||o.status}</span></header><h2>{o.product.title} × {o.quantity}</h2><p>消耗 {o.totalPoints} 积分 · {new Date(o.createdAt).toLocaleString('zh-CN')}</p><div className="redemption-address"><b>{o.address.name}　{o.address.phone}</b><p>{o.address.province}{o.address.city}{o.address.district}{o.address.detail}</p></div>{o.shipping&&<p>物流：{o.shipping.carrier}　{o.shipping.trackingNo}</p>}{o.status==='processing'&&<Button disabled={busy} onClick={()=>{setSelected(o);setCarrier('');setTrackingNo('');setShippingError('');}}>填写物流并发货</Button>}</article>):<p className="redemption-admin-empty">暂无{status?labels[status]:''}兑换订单</p>}<div className="redemption-toolbar"><Button variant="outline" disabled={loading||busy||offset===0} onClick={()=>setOffset(n=>Math.max(0,n-20))}>上一页</Button><Button variant="outline" disabled={loading||busy||!hasMore} onClick={()=>setOffset(n=>n+20)}>下一页</Button></div></>}
 <Dialog open={!!selected} onOpenChange={open=>{if(!open&&!busy)setSelected(null);}}><DialogContent><DialogTitle>确认兑换订单发货</DialogTitle><DialogDescription>请核对已寄出的快递信息，确认后用户可查看物流单号。</DialogDescription><p>{selected?.product.title} × {selected?.quantity}</p><label className="field"><span>快递公司</span><Input maxLength={40} value={carrier} disabled={busy} placeholder="例如：顺丰速运" onChange={e=>setCarrier(e.target.value)}/></label><label className="field"><span>运单号</span><Input maxLength={60} value={trackingNo} disabled={busy} onChange={e=>setTrackingNo(e.target.value)}/></label>{shippingError&&<p role="alert" className="redemption-admin-error">{shippingError}</p>}<Button disabled={busy||!carrier.trim()||!trackingNo.trim()} onClick={()=>void ship()}>{busy?'正在保存…':'确认发货'}</Button></DialogContent></Dialog>
 </main>;
}
