'use client';
/* oxlint-disable next/no-img-element */
import {useEffect,useRef,useState,type CSSProperties,type ReactNode} from 'react';
import {PanelsTopLeft,ImagePlus,ShoppingBag,Save,Upload,Eye,Plus,ArrowUp,ArrowDown,Trash2,ChevronRight,Monitor,SidebarIcon} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Switch} from '@/components/ui/switch';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {SidebarTrigger} from '@/components/ui/sidebar';
import './member-editor.css';
import MemberProductDetailEditor,{MemberProductDetail} from './member-product-detail-editor';
import './member-publish.css';
import {ops,uploadMedia} from '@/lib/ops-client';
import {memberDefaults,type MemberConfig,type MemberEntry,type MemberProduct,type MemberResult,type MemberPublication} from '@/lib/member';
import {memberPublishIssues,type MemberPublishIssue} from '@/lib/member-publish';

type Section='hero'|'entries'|'banner'|'products';
const sections:{id:Section;title:string;hint:string}[]=[{id:'hero',title:'顶部海报',hint:'一张大图，无二级页'},{id:'entries',title:'双列海报',hint:'两个入口，可设置二级页'},{id:'banner',title:'横幅海报',hint:'一张横图，无二级页'},{id:'products',title:'积分商品',hint:'商品、详情页与兑换说明'}];
const api=async(action:string,body?:unknown)=>await ops(action,body,{timeoutMs:30000}) as unknown as MemberResult;
function Field({title,children}:{title:string;children:ReactNode}){return <label className="field"><span>{title}</span>{children}</label>;}
function Picture({src,label,style}:{src:string;label:string;style?:CSSProperties}){return src?<img src={src} alt={label} style={style}/>:<div className="member-placeholder" style={style}><ImagePlus size={22}/><span>{label}</span></div>;}
export function MemberPreview({config,selected,onSelect,interactive=false}:{config:MemberConfig;selected?:Section;onSelect?:(id:Section)=>void;interactive?:boolean}){
 const [detail,setDetail]=useState<{kind:'entry'|'product';id:string}|null>(null);
 const entry=detail?.kind==='entry'?config.entries.items.find(e=>e.id===detail.id):null;
 const product=detail?.kind==='product'?config.products.items.find(p=>p.id===detail.id):null;
 function pick(id:Section){if(!interactive)onSelect?.(id);}
 return <div className="phone member-phone"><div className="phone-status"><b>9:41</b><span>● ▰ ▰</span></div><div className="phone-brand"><b>TOPUYI</b><span>会员中心</span><span className="capsule">••• │ ○</span></div><div className="phone-page member-preview-page">
 {detail&&(entry||product)?<article className="member-preview-article"><button className="member-back" onClick={()=>setDetail(null)}>‹ 返回会员中心</button><>{entry?<><Picture src={entry.image} label="封面图片"/><h2>{entry.title}</h2>{entry.content.map(b=>b.type==='image'?b.image&&<img key={b.id} src={b.image} alt="内容图片"/>:<p key={b.id}>{b.text}</p>)}</>:product&&<MemberProductDetail product={product}/>}</></article>:<>
 {config.hero.visible&&<section className={selected==='hero'?'member-selected':''} onClick={()=>pick('hero')}><Picture src={config.hero.image} label="顶部海报" style={{height:config.hero.height/2}}/></section>}
 {config.entries.visible&&<section className={'member-entry-grid '+(selected==='entries'?'member-selected':'')} onClick={()=>pick('entries')}>{config.entries.items.map(e=><button key={e.id} type="button" aria-label={e.title||'海报入口'} onClick={()=>{if(interactive&&e.enabled)setDetail({kind:'entry',id:e.id});}} style={{cursor:interactive&&!e.enabled?'default':undefined}}><Picture src={e.image} label={e.title||'入口海报'} style={{height:config.entries.height/2}}/></button>)}</section>}
 {config.banner.visible&&<section className={selected==='banner'?'member-selected':''} onClick={()=>pick('banner')}><Picture src={config.banner.image} label="横幅海报" style={{height:config.banner.height/2}}/></section>}
 {config.products.visible&&<section className={selected==='products'?'member-selected':''} onClick={()=>pick('products')}>{config.products.title&&<h3 className="member-products-heading">{config.products.title}</h3>}<div className="member-product-grid">{config.products.items.filter(p=>p.visible).map(p=><div className="member-product" key={p.id}><Picture src={p.image} label="商品图片"/><strong>{p.title||'商品标题'}</strong><div className="member-product-bottom"><b>{p.points>0?p.points+' 积分':'待填写积分'}</b><button type="button" onClick={()=>{if(interactive)setDetail({kind:'product',id:p.id});}}>兑换</button></div></div>)}</div>{!config.products.items.some(p=>p.visible)&&<div className="member-empty-products">添加积分商品后在这里展示</div>}</section>}
 </>}</div><div className="phone-tabs">{['首页','全部商品','会员中心','个人中心'].map((v,i)=><span key={v} className={i===2?'tab-on':''}><span>{['◇','▣','♔','○'][i]}</span>{v}</span>)}</div></div>;
}

export default function MemberEditor({onDirtyChange}:{onDirtyChange?:(dirty:boolean)=>void}){
 const [detailProductId,setDetailProductId]=useState<string|null>(null);
 const [config,setConfig]=useState<MemberConfig>(memberDefaults),ref=useRef(config),[selected,setSelected]=useState<Section>('hero');
 const [ready,setReady]=useState(false),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[saved,setSaved]=useState('尚未保存');
 const revision=useRef<string|null>(null),[publication,setPublication]=useState<MemberPublication>({revision:null,updatedAt:'',productCount:0,draftRevision:null});
 const [dialog,setDialog]=useState<'preview'|'publish'|null>(null),[publishReady,setPublishReady]=useState(false);
 const [publishError,setPublishError]=useState(''),[publishing,setPublishing]=useState(false),[showPublishIssues,setShowPublishIssues]=useState(false);
 const publishIssues=memberPublishIssues(config);
 const detailProduct=config.products.items.find(p=>p.id===detailProductId);
 const editPanel=useRef<HTMLElement>(null);
 async function load(){setBusy(true);try{const v=await api('memberLoad');const c=v.draft?.config||memberDefaults();setConfig(c);ref.current=c;revision.current=v.draft?.revision||null;setPublication(v.publication);setDirty(false);setReady(true);setSaved(v.draft?new Date(v.draft.updatedAt).toLocaleString('zh-CN')+' · '+v.draft.updatedBy:'尚未保存');setNotice('');}catch(e){setNotice(e instanceof Error?e.message:'会员草稿读取失败，请重试。');}finally{setBusy(false);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{onDirtyChange?.(dirty);},[dirty,onDirtyChange]);
 useEffect(()=>{if(!dirty)return;const h=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener('beforeunload',h);return()=>window.removeEventListener('beforeunload',h);},[dirty]);
 function change(update:(c:MemberConfig)=>MemberConfig){const next=update(ref.current);ref.current=next;setConfig(next);setDirty(true);}
 function section<K extends Section>(id:K,patch:Partial<MemberConfig[K]>){change(c=>({...c,[id]:{...c[id],...patch}}));}
 function entry(id:string,patch:Partial<MemberEntry>){change(c=>({...c,entries:{...c.entries,items:c.entries.items.map(e=>e.id===id?{...e,...patch}:e)}}));}
 function product(id:string,patch:Partial<MemberProduct>){change(c=>({...c,products:{...c.products,items:c.products.items.map(p=>p.id===id?{...p,...patch}:p)}}));}
 async function upload(file:File|undefined,update:(src:string)=>void){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024){setNotice('请选择 JPG、PNG 或 WebP 图片，每张最大 8MB。');return;}setBusy(true);try{update(await uploadMedia(file));setNotice('图片已上传，请保存会员中心共享草稿。');}catch(e){setNotice(e instanceof Error?e.message:'图片上传失败，请重试。');}finally{setBusy(false);}}
 function imageField(src:string,label:string,update:(src:string)=>void){return <div className="member-media-field"><label className={'upload-zone '+(src?'has-image':'')}>{src?<img src={src} alt={label}/>:<ImagePlus/>}<strong>{src?'替换'+label:'上传'+label}</strong><span>JPG / PNG / WebP，最大 8MB</span><input type="file" accept="image/jpeg,image/png,image/webp" aria-label={'上传'+label} onChange={e=>{void upload(e.target.files?.[0],update);e.target.value='';}}/></label>{src&&<Button type="button" variant="ghost" size="sm" onClick={()=>update('')}>移除图片</Button>}</div>;}
 async function save(){setBusy(true);setPublishError('');try{const v=await api('memberSave',{config:ref.current,expectedRevision:revision.current});setConfig(v.record.config);ref.current=v.record.config;revision.current=v.record.revision;setDirty(false);setSaved(new Date(v.record.updatedAt).toLocaleString('zh-CN')+' · '+v.record.updatedBy);setNotice('会员中心共享草稿已保存。点击“发布会员中心”后，小程序可读取最新内容。');}catch(e){const message=e instanceof Error?e.message:'保存失败，请重试。';setNotice(message);setPublishError('草稿保存遇到问题：'+message);}finally{setBusy(false);}}
 async function openPublish(){setDialog('publish');setShowPublishIssues(true);setPublishError('');setPublishReady(false);setBusy(true);try{const v=await api('memberStatus');setPublication(v);setPublishReady(true);}catch(e){setPublishError('无法确认云端发布状态：'+(e instanceof Error?e.message:'请稍后重试。'));}finally{setBusy(false);}}
 async function publish(){if(busy||dirty||!publishReady||!revision.current||memberPublishIssues(ref.current).length)return;setBusy(true);setPublishing(true);setPublishError('');try{const v=await api('memberPublish',{expectedDraftRevision:revision.current,expectedRevision:publication.revision});setPublication(v);setDialog(null);setNotice('会员中心已发布。已包含会员中心的新版本小程序，重新打开或下拉刷新即可看到。');}catch(e){setPublishReady(false);setPublishError('发布请求遇到问题：'+(e instanceof Error?e.message:'请稍后重试。'));}finally{setBusy(false);setPublishing(false);}}
 function editPublishIssue(issue:MemberPublishIssue){setSelected(issue.section);setDialog(null);setTimeout(()=>editPanel.current?.scrollIntoView({behavior:'smooth',block:'start'}),200);}
 function moveProduct(id:string,step:number){change(c=>{const items=[...c.products.items],i=items.findIndex(p=>p.id===id),to=i+step;if(i<0||to<0||to>=items.length)return c;[items[i],items[to]]=[items[to],items[i]];return {...c,products:{...c.products,items}};});}
 function moveContent(id:string,index:number,step:number){const e=ref.current.entries.items.find(e=>e.id===id);if(!e)return;const content=[...e.content],to=index+step;if(to<0||to>=content.length)return;[content[index],content[to]]=[content[to],content[index]];entry(id,{content});}
 return <>
 <main className="workspace"><header className="topbar"><div className="crumb"><SidebarTrigger/><span>店铺装修</span><ChevronRight size={15}/><b>会员中心</b></div><div className="top-actions"><Button variant="outline" disabled={busy} onClick={()=>{if(!dirty||window.confirm('重新读取会替换会员中心未保存的修改，继续？'))void load();}}>重新读取草稿</Button><Button variant="outline" disabled={!ready||busy} onClick={()=>setDialog('preview')}><Eye/>预览</Button><Button disabled={!ready||busy} onClick={()=>void save()}><Save/>{busy?'处理中…':'保存共享草稿'}</Button><Button disabled={!ready||busy} onClick={()=>void openPublish()}><Upload/>发布会员中心</Button></div></header>
 <div className="page-heading"><div><div className="title-line"><h1>会员中心装修</h1><span className="draft-tag">{dirty?'有未保存修改':'草稿'}</span></div><p>海报、会员活动与积分商品，一页管理。</p></div><div className="save-state">{ready?saved:'正在读取草稿…'}</div></div><div className="scope-note"><Monitor size={16}/><span>先保存共享草稿，再发布会员中心。发布后，体验版、审核版和正式版读取同一份会员内容。</span></div>{notice&&<output className="feedback" role="status">{notice}</output>}
 <div className="editor-grid member-editor-grid"><aside className="module-panel"><div className="panel-header"><b>页面区域</b><span>4 个</span></div><p className="panel-help">按参考图排列，点击编辑</p><div className="module-rows">{sections.map(s=><div key={s.id} className={'module-row '+(selected===s.id?'active':'')}><button className="module-select" onClick={()=>setSelected(s.id)}>{s.id==='products'?<ShoppingBag size={19}/>:<ImagePlus size={19}/>}<span><b>{s.title}</b><small>{s.hint}</small>{showPublishIssues&&publishIssues.some(i=>i.section===s.id)&&<small className="member-module-warning">有待完善内容</small>}</span></button></div>)}</div></aside>
 <section className="canvas"><div className="canvas-heading"><span><SidebarIcon size={16}/>手机实时预览</span><small>375 px</small></div><MemberPreview config={config} selected={selected} onSelect={setSelected}/><p className="canvas-tip">点击“预览”可查看海报二级页和积分商品详情</p></section>
 <aside className="properties" ref={editPanel}><div className="panel-header"><b>{sections.find(s=>s.id===selected)?.title}</b><span>编辑设置</span></div><fieldset disabled={!ready||busy}><div className="field-body"><div className="field switch-field"><span>显示该区域</span><Switch checked={config[selected].visible} aria-label="显示该区域" onCheckedChange={visible=>section(selected,{visible})}/></div>
 {selected!=='products'&&<Field title="图片高度（rpx）"><Input type="number" min={80} max={900} value={config[selected].height} onChange={e=>section(selected,{height:Number(e.target.value)})}/><small>支持 80–900 rpx，预览会实时调整。</small></Field>}
 {(selected==='hero'||selected==='banner')&&imageField(config[selected].image,selected==='hero'?'顶部海报':'横幅海报',image=>section(selected,{image}))}
 {selected==='entries'&&config.entries.items.map((e,n)=><div className="item-editor" key={e.id}><div className="item-top"><b>{n===0?'左侧海报':'右侧海报'}</b></div>{imageField(e.image,n===0?'左侧海报':'右侧海报',image=>entry(e.id,{image}))}<Field title="海报名称 / 二级页标题"><Input value={e.title} maxLength={80} onChange={v=>entry(e.id,{title:v.target.value})}/></Field><div className="field switch-field"><span>点击打开二级页</span><Switch checked={e.enabled} aria-label={'打开'+e.title+'二级页'} onCheckedChange={enabled=>entry(e.id,{enabled})}/></div>{e.enabled&&<><p className="member-field-help">封面和标题会显示在二级页顶部，下面可添加图文。</p>{e.content.map((b,i)=><div className="member-content-block" key={b.id}><div className="item-top"><b>{b.type==='text'?'文字':'图片'} {i+1}</b><div><Button size="icon" variant="ghost" aria-label="内容上移" disabled={!i} onClick={()=>moveContent(e.id,i,-1)}><ArrowUp size={14}/></Button><Button size="icon" variant="ghost" aria-label="内容下移" disabled={i===e.content.length-1} onClick={()=>moveContent(e.id,i,1)}><ArrowDown size={14}/></Button><Button size="icon" variant="ghost" aria-label="删除内容" onClick={()=>entry(e.id,{content:e.content.filter(x=>x.id!==b.id)})}><Trash2 size={14}/></Button></div></div>{b.type==='text'?<Field title="文字内容"><textarea maxLength={3000} value={b.text} onChange={v=>entry(e.id,{content:e.content.map(x=>x.id===b.id?{...x,text:v.target.value}:x)})}/></Field>:imageField(b.image,'二级页图片',image=>{const latest=ref.current.entries.items.find(x=>x.id===e.id)!;entry(e.id,{content:latest.content.map(x=>x.id===b.id?{...x,image}:x)});})}</div>)}<div className="member-inline-actions"><Button variant="outline" size="sm" disabled={e.content.length>=30} onClick={()=>entry(e.id,{content:[...e.content,{id:crypto.randomUUID(),type:'text',text:'',image:''}]})}><Plus/>添加文字</Button><Button variant="outline" size="sm" disabled={e.content.length>=30} onClick={()=>entry(e.id,{content:[...e.content,{id:crypto.randomUUID(),type:'image',text:'',image:''}]})}><ImagePlus/>添加图片</Button></div></>}</div>)}
 {selected==='products'&&<><Field title="区域标题（可留空）"><Input value={config.products.title} maxLength={60} onChange={e=>section('products',{title:e.target.value})}/></Field><p className="member-field-help">点击商品的“编辑详情页”可配置轮播图片与图文介绍，兑换说明选填。</p>{config.products.items.map((p,n)=><details className="item-editor member-product-editor" key={p.id} open={config.products.items.length===1?true:undefined}><summary>{n+1}. {p.title||'新积分商品'}</summary><div className="member-inline-actions"><Button variant="ghost" size="sm" disabled={!n} onClick={()=>moveProduct(p.id,-1)}><ArrowUp/>上移</Button><Button variant="ghost" size="sm" disabled={n===config.products.items.length-1} onClick={()=>moveProduct(p.id,1)}><ArrowDown/>下移</Button><Button variant="ghost" size="sm" onClick={()=>{if(window.confirm('删除这个积分商品？保存并发布后生效。'))section('products',{items:config.products.items.filter(x=>x.id!==p.id)});}}><Trash2/>删除</Button></div><div className="field switch-field"><span>展示商品</span><Switch checked={p.visible} aria-label={'展示'+(p.title||'商品')} onCheckedChange={visible=>product(p.id,{visible})}/></div>{imageField(p.image,'积分商品图片',image=>product(p.id,{image}))}<Field title="商品标题"><Input maxLength={80} value={p.title} onChange={e=>product(p.id,{title:e.target.value})}/></Field><Field title="所需积分"><Input type="number" min={1} max={99999999} step={1} value={p.points||''} placeholder="例如 9865" onChange={e=>product(p.id,{points:Number(e.target.value)})}/></Field><Button type="button" variant="outline" className="wide" onClick={()=>setDetailProductId(p.id)}><PanelsTopLeft/>编辑详情页</Button><p className="member-field-help">{(p.detailImages||[]).length} 张补充主图 · {(p.detailBlocks||[]).length} 项详情图文</p><Field title="商品介绍"><textarea maxLength={3000} value={p.description} onChange={e=>product(p.id,{description:e.target.value})}/></Field><Field title="兑换说明（选填）"><textarea maxLength={3000} placeholder="选填，可填写参与条件、兑换方式、领取安排等" value={p.exchangeInstructions} onChange={e=>product(p.id,{exchangeInstructions:e.target.value})}/></Field></details>)}<Button className="wide" variant="outline" disabled={config.products.items.length>=50} onClick={()=>section('products',{items:[...config.products.items,{id:crypto.randomUUID(),title:'',image:'',points:0,visible:true,description:'',exchangeInstructions:'',detailImages:[],detailBlocks:[]}]})}><Plus/>添加积分商品（{config.products.items.length}/50）</Button></>}
 </div></fieldset></aside></div></main>
 <Dialog open={!!dialog} onOpenChange={open=>!open&&setDialog(null)}><DialogContent className={dialog==='preview'?'preview-dialog':'admin-dialog'}><DialogTitle>{dialog==='preview'?'会员中心预览':'发布会员中心'}</DialogTitle><DialogDescription>{dialog==='preview'?'点击双列海报或兑换按钮，可预览对应内容。':'先检查页面内容，再发布已保存的会员中心草稿。'}</DialogDescription>{dialog==='preview'?<MemberPreview config={config} interactive/>:<div className="cloud-panel member-publish-panel">
 {publishIssues.length>0?<div className="member-publish-issues" role="alert"><h3>暂时无法发布，有 {publishIssues.length} 处内容需要完善</h3><p>开启显示的内容需要填写完整；暂不使用的区域或商品可以关闭显示。</p><ul>{publishIssues.map((issue,index)=><li key={issue.section+index}><div><strong>{issue.label}</strong><p>{issue.message}</p></div><Button variant="outline" size="sm" disabled={publishing} onClick={()=>editPublishIssue(issue)} aria-label={'去编辑'+issue.label}>去编辑</Button></li>)}</ul></div>:<p className="member-publish-valid">内容检查通过，未开启的区域无需补充图片或商品资料。</p>}
 {(dirty||!revision.current)&&<div className="member-publish-unsaved" role="status"><p>{dirty?'当前还有未保存的修改。保存共享草稿后才能发布。':'当前页面尚未保存。先保存共享草稿，再发布。'}</p><Button variant="outline" size="sm" disabled={busy} onClick={()=>void save()}>保存共享草稿</Button></div>}
 {busy&&!publishing&&<p role="status">正在检查或保存，请稍候…</p>}
 {publishError&&<div className="member-publish-error" role="alert"><strong>{publishError}</strong><p>尚未确认发布成功。请点击“重新检查”核对云端状态，再按提示处理。</p></div>}
 <p>本次发布：{config.products.visible?config.products.items.filter(p=>p.visible).length:0} 个积分商品</p><p>最近发布：{publication.updatedAt?new Date(publication.updatedAt).toLocaleString('zh-CN'):'尚未发布'}</p>
 <div className="member-inline-actions"><Button variant="outline" disabled={busy} onClick={()=>setDialog(null)}>返回编辑</Button><Button variant="outline" onClick={()=>void openPublish()} disabled={busy}>重新检查</Button><Button onClick={()=>void publish()} disabled={busy||dirty||!revision.current||!publishReady||publishIssues.length>0}>{publishing?'正在发布…':busy?'处理中…':'发布这份会员草稿'}</Button></div>
 </div>}</DialogContent></Dialog>
 <Dialog open={!!detailProduct} onOpenChange={open=>{if(!open&&!busy)setDetailProductId(null);}}><DialogContent className="member-detail-dialog"><DialogTitle>编辑积分商品详情页</DialogTitle><DialogDescription>编辑后点击“完成编辑”，再保存共享草稿并发布会员中心。</DialogDescription>{detailProduct&&<MemberProductDetailEditor key={detailProduct.id} product={detailProduct} busy={busy} onBusyChange={setBusy} onChange={update=>change(c=>({...c,products:{...c.products,items:c.products.items.map(p=>p.id===detailProduct.id?update(p):p)}}))}/>}<div className="member-detail-done"><Button disabled={busy} onClick={()=>setDetailProductId(null)}>{busy?'图片上传中…':'完成编辑'}</Button></div></DialogContent></Dialog>
 </>;
}
