const memberCloud=require('../../utils/member-cloud');
const redemption=require('../../utils/redemption-cloud');
const {isLoggedIn,goLoginPage}=require('../../utils/auth');
const mainImages=content=>[...new Set([content.image,...(content.detailImages||[])].filter(src=>typeof src==='string'&&src.trim()).map(src=>src.trim()))];
function decorate(kind,content){if(!content)return null;if(kind!=='product')return content;return {...content,mainImages:mainImages(content),detailBlocks:(content.detailBlocks||[]).filter(b=>b.type==='text'?b.text.trim():b.image)};}
function pickContent(config,kind,id){if(!config)return null;const product=kind==='product';const list=product?(config.products.visible?config.products.items:[]):(config.entries.visible?config.entries.items.filter(e=>e.enabled):[]);return decorate(kind,list.find(x=>x.id===id)||null);}
Page({
 data:{content:null,kind:'entry',imageIndex:0,loading:true,error:'',mediaError:false,quote:null,quoteLoading:false,quoteError:'',buttonText:'正在加载…',canRedeem:false,loggedIn:false,hasPending:false},
 onLoad(options){this._id=options.id||'';this._kind=options.kind==='product'?'product':'entry';const content=pickContent(memberCloud.peek().config,this._kind,this._id);this.setData({kind:this._kind,...(content?{content,loading:false,imageIndex:0}:{})});if(!content)this.loadContent();},
 onShow(){if(this._kind==='product')this.loadQuote();},
 onUnload(){this._sequence=(this._sequence||0)+1;this._contentSequence=(this._contentSequence||0)+1;},
 onPullDownRefresh(){Promise.all([this.loadContent(),this._kind==='product'?this.loadQuote():Promise.resolve()]).finally(()=>wx.stopPullDownRefresh());},
 async loadContent(){if(this._loading)return;const n=this._contentSequence=(this._contentSequence||0)+1;this._loading=true;if(!this.data.content)this.setData({loading:true,error:'',mediaError:false});try{const value=await memberCloud.load(),product=this._kind==='product';let content=pickContent(value.config,this._kind,this._id);if(!content&&this.data.hasPending&&this.data.quote)content=decorate(this._kind,{...this.data.quote.product,exchangeInstructions:''});if(product&&content&&this.data.quote)content=decorate(this._kind,{...this.data.content||{},...content,points:this.data.quote.product.points});const same=content&&this.data.content&&(content.id===this.data.content.id)&&(content.title===this.data.content.title)&&(JSON.stringify(content.mainImages||content.image)==JSON.stringify(this.data.content.mainImages||this.data.content.image));if(n===this._contentSequence)this.setData({...(same?{}:{content,imageIndex:content&&this.data.content?Math.min(this.data.imageIndex,Math.max(0,(content.mainImages||[]).length-1)):0}),kind:this._kind,error:value.error||(content?'':'该内容已下线或尚未发布')});}catch(e){if(n===this._contentSequence)this.setData({error:e.message||'内容加载失败，请重试'});}finally{this._loading=false;if(n===this._contentSequence)this.setData({loading:false});}},
 async loadQuote(){const n=this._sequence=(this._sequence||0)+1;const pending=isLoggedIn()?wx.getStorageSync(redemption.pendingKey(this._id)):null;if(pending){this.setData({quote:pending.quote,hasPending:true,quoteLoading:false,quoteError:'',buttonText:'查看兑换结果',canRedeem:true,loggedIn:true});return;}this.setData({hasPending:false,quoteLoading:true,quoteError:'',canRedeem:false,loggedIn:isLoggedIn()});try{const quote=await redemption.call('redemptionQuote',{productId:this._id});if(n!==this._sequence)return;const loggedIn=isLoggedIn(),patch={quote,loggedIn,...redemption.actionState(quote,loggedIn)};if(!this.data.content&&quote.product){const content=decorate(this._kind,{...quote.product,exchangeInstructions:quote.product.exchangeInstructions||''});if(content)content.mainImages=mainImages(content);patch.content=content;}else if(this.data.content&&quote.product&&quote.product.points!==this.data.content.points)patch.content={...this.data.content,points:quote.product.points};this.setData(patch);}catch(e){if(n===this._sequence)this.setData({quote:null,quoteError:e.message||'兑换信息加载失败',buttonText:e.code==='OFF_SHELF'?'商品已下架':'重新加载',canRedeem:false});}finally{if(n===this._sequence)this.setData({quoteLoading:false});}},
 redeem(){if(this.data.quoteLoading)return;if(this.data.hasPending){wx.navigateTo({url:'/pages/redemption-checkout/redemption-checkout?id='+encodeURIComponent(this._id)});return;}if(this.data.quoteError)return this.loadQuote();if(!isLoggedIn()||!this.data.quote?.isMember){goLoginPage('登录后使用积分兑换商品');return;}if(!this.data.canRedeem)return;wx.navigateTo({url:'/pages/redemption-checkout/redemption-checkout?id='+encodeURIComponent(this._id)});},
 orders(){if(!isLoggedIn()){goLoginPage('登录后查看积分兑换订单');return;}wx.navigateTo({url:'/pages/redemption-orders/redemption-orders'});},
 onMediaError(){this.setData({mediaError:true});},
 onImageChange(e){const index=Number(e.detail.current);if(Number.isInteger(index)&&index>=0&&index<(this.data.content?.mainImages?.length||0))this.setData({imageIndex:index});},
 previewImage(e){const content=this.data.content;if(!content)return;const urls=[...new Set([...(this._kind==='product'?content.mainImages||mainImages(content):[content.image]),...(this._kind==='product'?content.detailBlocks||[]:content.content||[]).filter(x=>x.type==='image').map(x=>x.image)].filter(Boolean))],current=e.currentTarget.dataset.src;if(urls.includes(current))wx.previewImage({current,urls});}
});
